spring:
  application:
    name: budgetsphere-agents
  
  ai:
    ollama:
      init:
        pull-model-strategy: always
        timeout: 60s
        max-retries: 1
        embedding:
          additional-models: nomic-embed-text
      base-url: http://localhost:11434
      chat:
        model: qwen3:8b
        options:
          temperature: 0.7
          top-p: 0.9
          max-tokens: 2048
        enabled: true

server:
  port: 8080

logging:
  level:
    com.budgetsphere: DEBUG
    org.springframework.ai: INFO
  pattern:
    console: "%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

